### ISSUE TITLE
Webhook unsubscribed in some time

### ISSUE THREAD

**Issue by annalauraaldlc** [aspnet/WebHooks#103] opened 2017-01-18 12:29 UTC
Hi,

Initially, sorry for my english.
So, I implemented a Custom WebHook, no problem here. It's worked perfectly.
But, after some time, my WebHookReceiver stopped receiving notifications. It's occured two times.
I register Receiver again, and all worked as before.

Any ideia about what cause this?
It is possible expire WebHookReceiver registry?

**Comment by HenrikFrystykNielsen** [comment] 2017-01-18 16:13
Where do you store the registrations? In Azure Table Storage, SQL, or somewhere else? The easiest would be to see what data is in there.

**Comment by annalauraaldlc** [comment] 2017-01-18 20:24
In local SQL Database.
I registered three times the same receiver, because ocurred this problem.  
The Data in Table is below:
![image](https://cloud.githubusercontent.com/assets/13685507/22081591/4a2c61de-ddab-11e6-82cb-196772ed28b5.png)

**Comment by mprigge** [comment] 2017-10-05 14:02
I think I am seeing the same problem. The registrations are still in the database, but after a period of time (overnight, in this case), the registrations no longer seem to work and aren't listed in the /api/webhooks/registrations output. I don't see any facility for timing out registrations, so this is obviously odd behavior.

@annalauraaldlc - did you find a solution to this?

**Comment by mprigge** [comment] 2017-10-05 16:02
Nevermind - my problem ended up being a DataProtection issue that reared its head after the app pool recycled. The registrations were there, but couldn't be decrypted because the data protection key used to encrypt them wasn't being written anywhere (the fallback behavior when the app pool isn't allow to modify the registry or write to AppData).  I added some bits to reconfigure the data protector to write keys into a directory that the app pool has access to and that solved the problem.

**Comment by dougbu** [comment] 2018-01-17 02:37
Thank you for your feedback. We're closing this issue as the behavior discussed seems to be by design. And, other than @mprigge's key management problem, no updates have been provided in a timely manner and we have been unable to reproduce the issue. If you have more details and are encountering this issue please add a new reply and re-open the issue.

**Closed by dougbu** 2018-01-17 02:37 UTC
