### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by pradt** [aspnet/WebHooks#63] opened 2016-05-21 01:56 UTC
I'm receiving a 500 Internal Server error when using Webhooks with Stripe. I've tried to use remote debugging on ExecuteAsync but this is happening before this call. 

Actual message from postman 

{
  "Message": "WebHook receiver 'Stripe' could not process WebHook due to error: Object reference not set to an instance of an object."
}

I've used the instructions from the video, but altered it for Stripe. I've updated global.asax to register Webhooks.

**Comment by HenrikFrystykNielsen** [comment] 2016-05-21 20:44
I tried it out and can get the *test* event just fine. I assume you are not just trying test events though.

If you have the source (or enabled source debugging) you can set a breakpoint in StripeWebHookReceiver.ReceiveAsync (or catch exceptions) -- that should lead you to what is going on. 

Do you get any other entries in the trace messages?

**Comment by pradt** [comment] 2016-05-22 00:54
Hi I was trying the test events (charge.succeeded) via the stripe dashboard > Account settings > webhooks. 

I did a search of the project for StripeWebHookReceiver.ReceiverAsync and ReceiverAsync and it could not be found. 

I followed the https://www.youtube.com/watch?v=gbr-wZVl6d4 did the tasks (apart from the specific providers tasks) exactly.

**Comment by HenrikFrystykNielsen** [comment] 2016-05-22 15:17
I see the issue -- it's that the initializer function WebHookConfig.Register(...) is not called in the server setup path. If you add this line `WebHookConfig.Register(config);` to the end of WebApiConfig.Register then it works.

@bradygaster -- where is WebHookConfig.Register() normally called in the template?

Henrik

**Comment by HenrikFrystykNielsen** [comment] 2016-05-22 17:48
Btw, this should now be easier to diagnose: 39558cd49fa0340e630399f8e27b0107752efcf8

**Comment by bradygaster** [comment] 2016-05-23 16:23
@HenrikFrystykNielsen the code for that template is here. If it needs a pull request feel free to send me one. https://github.com/bradygaster/AspNet.WebHooks.ConnectedService/blob/master/AspNet.WebHooks.ConnectedService/Content/WebHookHandler.tt

**Comment by dougbu** [comment] 2017-11-22 18:19
Closing as invalid since the problem is external to this repo.

**Closed by dougbu** 2017-11-22 18:19 UTC
Labels: invalid, receivers
