### ISSUE TITLE
Flaky test: WebHookAction_NonPost_IsNotAllowed

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/WebHooks#314] opened 2018-07-25 19:05 UTC
This test [fails](http://aspnetci/viewLog.html?buildId=514940&buildTypeId=XPlat_Mac_MacUniverseCoreCLR) occasionally with the following error:
```
Microsoft.AspNetCore.Routing.Matchers.AmbiguousMatchException : The request matched multiple endpoints. Matches: 
SlackCoreReceiver.Controllers.SlackController.SlackForCommand (SlackCoreReceiver)
SlackCoreReceiver.Controllers.SlackController.SlackForTrigger (SlackCoreReceiver)
SlackCoreReceiver.Controllers.SlackController.Slack (SlackCoreReceiver)
   at Microsoft.AspNetCore.Routing.EndpointConstraints.EndpointConstraintEndpointSelector.SelectAsync(HttpContext httpContext, IEndpointFeature feature, CandidateSet candidates)
   at Microsoft.AspNetCore.Routing.Matchers.DfaMatcher.MatchAsync(HttpContext httpContext, IEndpointFeature feature)
   at Microsoft.AspNetCore.Routing.GlobalRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.TestHost.HttpContextBuilder.<>c__DisplayClass10_0.<<SendAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.TestHost.ClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Testing.Handlers.CookieContainerHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Testing.Handlers.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.AspNetCore.WebHooks.FunctionalTest.SlackCoreReceiverTest.WebHookAction_NonPost_IsNotAllowed(HttpMethod method) in /_/test/Microsoft.AspNetCore.WebHooks.FunctionalTest/SlackCoreReceiverTest.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by ryanbrandenburg** [comment] 2018-07-25 19:05
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=514940&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

**Comment by ryanbrandenburg** [comment] 2018-07-25 19:29
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=514945&buildTypeId=XPlat_Windows_Win8_Universe).

**Comment by ryanbrandenburg** [comment] 2018-07-25 19:32
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=514893&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

**Comment by ryanbrandenburg** [comment] 2018-07-25 19:39
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=514895&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

**Comment by Eilon** [comment] 2018-07-25 20:29
@dougbu - Please use this workflow to address this flaky test issue, including checking applicable checkboxes and filling in the applicable "TODO" entries:

* Is this test failure caused by product code flakiness? (Either this product, or another product this test depends on.)
  * [ ] File a bug against the product (TODO: Link to other bug)
  * Is it possible to change the test to avoid the flakiness?
    * Yes? Go to the "Change the test!" section.
    * No?
      * [ ] Disable the test (TODO: Link to PR/commit)
      * [ ] Wait for other bug to be resolved
      * [ ] Wait for us to get build that has the fix
      * [ ] Re-enable our test (TODO: Link to PR/commit)
      * [ ] Close this bug

* Is it that the test itself is flaky? This includes external transient problems (e.g. remote server problems, file system race condition, etc.)
  * Is there is a way to change our test to avoid this flakiness?
    * Yes? Change the test!
      * [ ] Change the test to avoid the flakiness, for example by using a different test strategy, or by adding retries w/ timeouts (TODO: Link to PR/commit)
      * [ ] Run the test 100 times locally as a sanity check.
      * [ ] Close this bug
    * No?
      * [ ] Delete the test because flaky tests are not useful (TODO: Link to PR/commit)

**Comment by dougbu** [comment] 2018-07-25 20:49
See #318 for product bug

**Comment by ryanbrandenburg** [comment] 2018-07-25 21:13
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=515163&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment] 2018-07-25 21:16
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=514938&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment] 2018-07-25 23:02
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=515414&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment] 2018-07-25 23:04
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=515284&buildTypeId=XPlat_HighSierraOsxUniverse).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment] 2018-07-25 23:30
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=515280&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment] 2018-07-25 23:54
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=515142&buildTypeId=XPlat_Windows_Win10Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment] 2018-07-26 01:00
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=515667&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment] 2018-07-26 01:24
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=515586&buildTypeId=Lite_UniverseTest).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment] 2018-07-26 03:01
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=515731&buildTypeId=XPlat_Mac_MacUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment] 2018-07-26 03:03
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=515729&buildTypeId=XPlat_Linux_UbuntuUniverseCoreCLR).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment] 2018-07-26 05:21
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=515716&buildTypeId=XPlat_Windows_Win7_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Comment by ryanbrandenburg** [comment] 2018-07-26 07:30
WebHookAction_NonPost_IsNotAllowed [failed again](http://aspnetci/viewLog.html?buildId=515720&buildTypeId=XPlat_Windows_Win2008r2_Universe).

This comment was made automatically. If there is a problem contact @ryanbrandenburg.

**Closed** 2018-08-03 01:42 UTC
Labels: Flaky

**Comment by dougbu** [comment] 2018-08-03 01:45
@rynowak much appreciated.

Is this `done`? And, should the workflow [above](https://github.com/aspnet/WebHooks/issues/314#issuecomment-407885062) be updated?
