### ISSUE TITLE
Strong Naming Issue

### ISSUE THREAD

**Issue by RealDotNetDave** [aspnet/WebHooks#135] opened 2017-05-03 15:36 UTC
None of the sites work for me. I keep getting this:

Could not load file or assembly 'Microsoft.AspNet.WebHooks.Common' or one of its dependencies. Strong name signature could not be verified.  The assembly may have been tampered with, or it was delay signed but not fully signed with the correct private key. (Exception from HRESULT: 0x80131045)

**Comment by HenrikFrystykNielsen** [comment] 2017-05-03 18:36
Run build.cmd from the command line :)

**Comment by RealDotNetDave** [comment] 2017-05-04 16:14
Great. Thanks.

**Comment by garora** [comment] 2017-05-08 07:38
Sorry for interference. Is this issue related to is: [#92](https://github.com/aspnet/WebHooks/issues/92) ?

**Comment by HenrikFrystykNielsen** [comment] 2017-05-15 17:51
Hi @garora, no it isn't. I haven't heard anything on that front :(

**Comment by garora** [comment] 2017-05-15 18:33
Thanks for head's up. I am still waiting on that. It a quite long time now
:(

**Comment by dougbu** [comment] 2017-11-06 02:32
This looks like a duplicate of #125. Both questions should be resolved following @HenrikFrystykNielsen's advice [here](https://github.com/aspnet/WebHooks/issues/135#issuecomment-298997999) or [here](https://github.com/aspnet/WebHooks/issues/125#issuecomment-287879987).

**Comment by dougbu** [comment] 2017-11-22 18:52
Answered question is a duplicate of #125

**Closed by dougbu** 2017-11-22 18:52 UTC
Labels: duplicate, question
