### ISSUE TITLE
Dosent work for multiple stripe accounts

### ISSUE THREAD

**Issue by skimonkey** [aspnet/WebHooks#105] opened 2017-01-30 22:27 UTC
You can open multiple stripe accounts under the one login profile, each account gets its own set of api keys. The webhooks willl only working against the initial account. If you switch to another account, and set the correct secret key in the web.config it does not work. It always rejects the event as invalid even though it is a valid event

{
  "Message": "The ID 'evt_19hnL4LdhGUIe7s6LxbGyl83' could not be resolved for an actual event."
}

**Comment by HenrikFrystykNielsen** [comment] 2017-01-30 23:50
Can you try and use the 'direct' mode of the Stripe receiver: it doesn't do a follow up GET request to get the actual event data. For details, please see fdc6a7fa059eed2a6ceca39aece06898c18a0f84

Hope this helps!

Henrik

**Comment by jsvahn** [comment] 2017-03-24 09:56
Did you get any explanation to this issue? We are having the same error, though we only have one account. The same key and event combination works if I run it with curl, so it seems to me that the key implementation here simply is broken for Stripe?

**Comment by dougbu** [comment] 2017-10-04 17:27
Is this a dupe of #63?

**Comment by dougbu** [comment] 2017-10-04 17:52
Never mind, #63 is unrelated.

**Comment by dougbu** [comment] 2017-10-04 18:09
Storing per-account keys in application settings is too static for Connect platform implementations. (Account WebHooks won't hit #63.) It's particularly telling that `StripeWebHookReceiver` does not reference a Connect event's `account` property.

Probably need to wrap the `GetReceiverConfig(...)` call in a lower-level extensibility point than the current (`virtual`) `StripeWebHookReceiver.GetEventDataAsync(...)` method. Then, a complete Connect WebHook application could easily hook up an account database that get's updated as accounts are registered and removed.

**Comment by dougbu** [comment] 2017-11-28 23:18
#163 should fix this issue. Closing as a duplicate.

**Closed by dougbu** 2017-11-28 23:18 UTC
Labels: receivers
