### ISSUE TITLE
Duplicated registrations with Custom Sql Storage

### ISSUE THREAD

**Issue by rubentacastro02** [aspnet/WebHooks#100] opened 2016-11-30 16:37 UTC
When you register a webhook receiver with sql storage it allows duplicated registers of the same receiver, causing it to receive multiple messages when the event he was listening to occurs.

I use this example:
https://blogs.msdn.microsoft.com/webdev/2015/11/07/updates-to-microsoft-asp-net-webhooks-preview/

This is a bug or I have made somthing wrong?

**Comment by HenrikFrystykNielsen** [comment] 2016-12-26 20:02
You mean that users can register the same WebHook URI multiple times? Yes, that's correct, we don't prevent the same URI to be registered multiple times.

**Comment by dougbu** [comment] 2018-01-17 02:38
Thank you for your feedback. We're closing this issue as the current behavior discussed seems to be by design.

**Closed** 2018-01-17 02:41 UTC
Labels: question
