### ISSUE TITLE
Fails to fetch the event from Stripe

### ISSUE THREAD

**Issue by bjomi** [aspnet/WebHooks#128] opened 2017-03-24 11:42 UTC
Hi,

we're using the Stripe receiver and we get an error when trying to fetch the actual event from Stripe (indirect mode). The error we get from Stripe is this:

The ID 'evt_<eventId>' could not be resolved for an actual event

So, something goes wrong when making the get request to Stripe in the GetEventDataAsync method. The MS_WebHookReceiverSecret_Stripe key is set to our secret test key from Stripe (in the form sk_test_<secret>).

When we make a simple request from cURL we do get the event back.

So, either something is wrong in the WebHooks code for Stripe or we do something wrong that is not obvious for us. Very grateful for advice here.

Best regards,
Björn Milton

**Comment by bjomi** [comment] 2017-03-30 08:18
Anybody got an idea about this issue?

**Comment by HenrikFrystykNielsen** [comment] 2017-03-31 21:20
Can you try and use the 'direct data' version of Stripe which doesn't get the data but just uses the data present in the event directly?

**Comment by bjomi** [comment] 2017-04-03 08:19
Thanks for your reply Henrik!

Yeah, we could use the "direct data" version. But we would like to follow best practices for Stripe, and they say that you should fetch the event again (as you probably know). When reading the code I can't see anything obvious that goes wrong when fetching the event from Stripe. Still something happens that we can't pin down. Have you seen or heard that this piece of code have worked before? Have you ran it yourself? Just trying to figure out if we do something wrong (which I have a hard time to identify) or if there indeed is some issue with the code.

**Comment by HenrikFrystykNielsen** [comment] 2017-04-04 17:56
Hmm, I don't have a strong idea here. I do know they say that for best practice but it might be useful to at least try the other way to see if that works. If you use an appropriate code in the URI then it should be ok.

**Comment by bjomi** [comment] 2017-04-05 11:11
Yeah, we're going the direct route for now. That works, and running if over an SSL endpoint in combination with the secret code.

But it would be interesting to understand why the other approach does not work.

In any case, thanks for your input.

**Comment by monireddy18** [comment] 2017-10-02 14:08
Hi,
@bjomi 
I found a similar issue in our Stripe integration code as well. Do you have any update on this issue yet? 

Best Regards,
Monika

**Comment by dougbu** [comment] 2017-10-04 18:11
This sounds similar to #105. @bjomi and @monireddy18 are you using Connect WebHooks? Account WebHooks shouldn't hit this issue if it's a dupe of #105.

**Comment by bjomi** [comment] 2017-10-05 06:15
@monireddy18 no, nothing new regarding this. We haven't looked deeper into it.

@dougbu yeah, we identified it as a possibly related issue at the time too. But I don't now. We are not using multiple accounts so it might also be totally unrelated.

**Comment by dougbu** [comment] 2017-11-28 23:18
#163 should fix this issue. Closing as a duplicate.

**Closed by dougbu** 2017-11-28 23:18 UTC
Labels: receivers
